[package]
name = "compiler"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
itertools = "0.11.0"
regex = "1.9.4"
strum = { version = "0.25.0", features = ["std", "derive"] }
strum_macros = "0.25.2"
